# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OdinWriter < Formula
  desc "CLI que converte episódios de podcast e vídeos do YouTube em artigos para websites"
  homepage "https://github.com/mguilhermetavares/odin-writer"
  version "1.0.1"
  license "MIT"

  depends_on "ffmpeg" => :optional
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.1/odin-writer_darwin_amd64.tar.gz"
      sha256 "29390f417baca397c3950326a59bca246bc0095c2b5b07fb5b0e43dcf890ce49"

      define_method(:install) do
        bin.install "odin-writer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.1/odin-writer_darwin_arm64.tar.gz"
      sha256 "d3b06d0ccdadb8e4e4104d931a251d583a99ebc972e549b54b0580587a4f39ab"

      define_method(:install) do
        bin.install "odin-writer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.1/odin-writer_linux_amd64.tar.gz"
      sha256 "5d882c84375fcbe244eba244d58af50f8f04dcce0e3bdafc2b3c884c00ec84a1"
      define_method(:install) do
        bin.install "odin-writer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.1/odin-writer_linux_arm64.tar.gz"
      sha256 "dc0d9b00a076e1bc29d16cead6410a21f8fd0d27a385994c04d0efdc973a66a6"
      define_method(:install) do
        bin.install "odin-writer"
      end
    end
  end

  test do
    system "#{bin}/odin-writer", "--version"
  end
end
