# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OdinWriter < Formula
  desc "CLI que converte episódios de podcast e vídeos do YouTube em artigos para websites"
  homepage "https://github.com/mguilhermetavares/odin-writer"
  version "1.0.3"
  license "MIT"

  depends_on "ffmpeg" => :optional
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.3/odin-writer_darwin_amd64.tar.gz"
      sha256 "57d00304b21c08cbc8a1afcd53548ec17b25eb6a51b63ee563900bb292f6a17a"

      define_method(:install) do
        bin.install "odin-writer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.3/odin-writer_darwin_arm64.tar.gz"
      sha256 "c691f4b11ec8765e3df7dead0aa36b86743a8077a970e2ef9108ae00b2317d09"

      define_method(:install) do
        bin.install "odin-writer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.3/odin-writer_linux_amd64.tar.gz"
      sha256 "e19b381a38e51d98dec73cb1a13624623b9a6f95559cf78419e6888ae0b0b063"
      define_method(:install) do
        bin.install "odin-writer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.3/odin-writer_linux_arm64.tar.gz"
      sha256 "f0d91b26fb3f2cb1f9de3a3d01494228dabe7512c3f24c124a3ee3df53b35b9e"
      define_method(:install) do
        bin.install "odin-writer"
      end
    end
  end

  test do
    system "#{bin}/odin-writer", "--version"
  end
end
