# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OdinWriter < Formula
  desc "CLI que converte episódios de podcast e vídeos do YouTube em artigos para websites"
  homepage "https://github.com/mguilhermetavares/odin-writer"
  version "1.0.10"
  license "MIT"

  depends_on "ffmpeg" => :optional
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.10/odin-writer_darwin_amd64.tar.gz"
      sha256 "42e08590066f055908fa7c44c253f1c5b95e64bfd50ff458b480adc385f5207f"

      define_method(:install) do
        bin.install "odin-writer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.10/odin-writer_darwin_arm64.tar.gz"
      sha256 "cb072d9c4841856db6577b79f7c49cec0c5afa3001e2f2f8958f04a2233733f8"

      define_method(:install) do
        bin.install "odin-writer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.10/odin-writer_linux_amd64.tar.gz"
      sha256 "650fe9bc70ec43be16f112ef03e0f1e77dc29232af24be090630e5b2b66a7c90"
      define_method(:install) do
        bin.install "odin-writer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mguilhermetavares/odin-writer/releases/download/v1.0.10/odin-writer_linux_arm64.tar.gz"
      sha256 "5f38482ded926b4f286925b73d66065dc690d65493943354bc1f7caf7693c906"
      define_method(:install) do
        bin.install "odin-writer"
      end
    end
  end

  test do
    system "#{bin}/odin-writer", "--version"
  end
end
